services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grubzo
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d grubzo"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5433:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/config
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis/redis-stack-server:7.4.0-v7-x86_64
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "5434:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo_container
    restart: unless-stopped
    ports:
      - "4318:4318"
      - "3100:3100"
    volumes:
      - ./data/tempo:/tmp/tempo_traces
      - ./metrics/tempo.yaml:/etc/tempo/tempo.yaml
    command: ["-config.file=/etc/tempo/tempo.yaml"]

  loki:
    image: grafana/loki:latest
    container_name: loki_container
    restart: unless-stopped
    ports:
      - "3200:3100"
    volumes:
      - ./data/loki:/loki
      - ./loki.yaml:/etc/loki/local-config.yaml
    command: ["-config.file=/etc/loki/local-config.yaml"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "3300:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - "5435:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      tempo:
        condition: service_started
    volumes:
      - ./data/grafana:/var/lib/grafana
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./data/ollama:/root/.ollama
  #   restart: unless-stopped
  # ollama-pull:
  #   image: ollama/ollama
  #   container_name: ollama-pull
  #   volumes:
  #     - ./data/ollama:/root/.ollama
  #   entrypoint: >
  #     /bin/sh -c "ollama serve & sleep 5 && ollama pull mistral && kill %1"
  #   depends_on:
  #     - ollama
  #   restart: "no"
